database: &database
  adapter: postgresql
  host: localhost
  port: 5432
  timeout: 5000
  database: sequent_sinatra_db
  schema_search_path: "event_store, <%= InvoicingApp::VIEW_PROJECTION.schema_name %>"

development:
  <<: *database
  pool: 5

test:
  <<: *database
  pool: 5
  database: sequent_sinatra_test_db
